export const PREV_WEEK = 'PREV_WEEK'
export const NEXT_WEEK = 'NEXT_WEEK'
export const TOGGLE_WEEKEND = 'TOGGLE_WEEKEND'

export const SYNC_GOOGLE_CALENDAR_REQUEST = 'SYNC_GOOGLE_REQUEST'
export const SYNC_GOOGLE_CALENDAR_CLIENT_INIT_COMPLETE = 'SYNC_GOOGLE_REQUEST_CLIENT_INIT_COMPLETE'
export const SYNC_GOOGLE_CALENDAR_SIGNED_IN = 'SYNC_GOOGLE_SIGNED_IN'
export const SYNC_GOOGLE_CALENDAR_COMPLETE = 'SYNC_GOOGLE_COMPLETE'

export const SET_AVAILABILITY = 'SET_AVAILABILITY'